spring:
  application:
    name:
      first-app
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
      bootstrap-servers: localhost:9092
server:
  port:
    8001
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:9000/eureka

ribbon:
  eureka:
    enabled: false

second-app:
  ribbon:
    listOfServers: localhost:8002

